FROM golang:1.23-alpine AS builder

RUN apk add --no-cache git make

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o gocron-node ./cmd/node

FROM alpine:latest

RUN apk add --no-cache ca-certificates tzdata && \
    addgroup -S app && \
    adduser -S -g app app

WORKDIR /app

COPY --from=builder /app/gocron-node .

RUN chown -R app:app ./

EXPOSE 5921

USER app

ENTRYPOINT ["/app/gocron-node"]
